#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      author: Joel W. King, @joelwking
#
#      description: Breached user check, verify if the username, email or phone number has
#                   been exposed in a security breach. 
#
#      usage:  
#
#        ansible-playbook pb.breach_user_check.yml -e 'email=bob@example.com' -e 'phone_number=9197079300' -e 'username=bob'
# 
#          use `--skip-tags sendmail` to avoid sending an email.
#
- name: Breached User Check
  connection: local
  hosts: localhost
  gather_facts: false

  vars: 
    # Subject of the investigation
    email: "bob@example.net"
    phone_number: 919-707-9300
    username: whitehead

    # Email (results) receipient
    receipient: jking@blueally.com
    
    pangea_anchor: &pangea_opts
      domain: "{{ lookup('ansible.builtin.env', 'PANGEA_DOMAIN') }}"
      token: "{{ lookup('ansible.builtin.env', 'PANGEA_TOKEN') }}"

  tasks:
    - name: User Intel email
      netcraftsmen.pangea.intel:
        <<: *pangea_opts
        action: user
        parameters:
          email: '{{ email }}'
          raw: true
      register: pangea_email
      tags: ['email']
    
    - name: User Intel username
      netcraftsmen.pangea.intel:
        <<: *pangea_opts
        action: user
        parameters:
          username: '{{ username }}'
          raw: true
      register: pangea_username
      tags: ['username']

    - name: User Intel phone number
      netcraftsmen.pangea.intel:
        <<: *pangea_opts
        action: user
        parameters:
          phone_number: '{{ phone_number }}'
          raw: true
      register: pangea_phone
      tags: ['phone']      

    - name: View output sample results
      ansible.builtin.debug:
        msg:
          - 'Phone: {{ phone_number }} {{ pangea_phone.data.summary }}'
          - 'Username: {{ username }} {{ pangea_username.data.summary }}'
          - 'Email: {{ email }} {{ pangea_email.data.summary }}'

    - name: Write files containing the returned data for additional analysis
      ansible.builtin.copy:
        content: '{{ item.data | to_yaml }}'
        dest: '{{ playbook_dir }}/files/{{ item.fname }}.yml'
      loop:
        - '{ "data": {{ pangea_phone }}, "fname": "phone"}'
        - '{ "data": {{ pangea_username }}, "fname": "username"}'
        - '{ "data": {{ pangea_email }}, "fname": "email"}'

    - name: Send email
      ansible.builtin.include_tasks:
        file: '{{ playbook_dir }}/task.email.yml'
      vars:
        to_email: '{{ receipient }}'
        reply_to_email:  no_reply@example.net
        subject_email: Automated User Breach Intelligence  
        body_email: 'Investigation results, if email address ({{ email }}), username ({{ username }}), phone number ({{ phone_number }}) were exposed in a security breach.'
        attachments_email: 
          - '{{ playbook_dir }}/files/email.yml'
          - '{{ playbook_dir }}/files/phone.yml'
          - '{{ playbook_dir }}/files/username.yml'
      tags: ['sendmail']