#!/usr/bin/env ansible-playbook
---
#
#      Copyright (c) 2023 BlueAlly NetCraftsmen, LLC
#      All rights reserved.
#
#      author: Joel W. King, @joelwking
#
#      description: Functional tests of pangea User, Domain and URL intel module
#
#      usage:  
#
#        ansible-playbook pb.intel_test.yml -v
# 

- name: Functional tests of the Pangea collection
  connection: local
  hosts: localhost
  gather_facts: false

  vars: 
    token: "{{ lookup('ansible.builtin.env', 'PANGEA_TOKEN') }}"
    domain: "{{ lookup('ansible.builtin.env', 'PANGEA_DOMAIN') }}"

  tasks:
    - name: User Intel email
      netcraftsmen.pangea.intel:
        token: '{{ token }}'
        domain: aws.us.pangea.cloud
        logger: true
        action: user
        parameters:
          email: "bob@example.net"
      register: pangea
      tags: ['email']
    
    - name: View output
      ansible.builtin.debug:
        msg:
          - 'request id {{ pangea.data.request_id }}'
          - 'breach_count {{ pangea.data.result.data.breach_count }}'
          - 'summary / status  {{ pangea.data.summary }} {{ pangea.data.status }}'

    - name: User Intel IP
      netcraftsmen.pangea.intel:
        token: '{{ token }}'
        domain: '{{ domain }}'
        action: user
        parameters:
          ip: 192.0.2.1
          raw: true
          verbose: true
          start: "2022-05-15"
          end: "2023-01-15"
          provider: spycloud
          domain: "737updatesboeing.com"  # Will be ignored, not valid under user action
      register: pangea
      tags: ['ip']

    - name: Domain reputation
      netcraftsmen.pangea.intel:
        token: '{{ token }}'
        domain: '{{ domain }}'
        action: domain
        parameters:
          domain: "737updatesboeing.com"
          provider: domaintools
          raw: false
          verbose: true
      register: pangea
      tags: ['domain']

    - name: URL reputation
      netcraftsmen.pangea.intel:
        token: '{{ token }}'
        domain: '{{ domain }}'
        action: url
        parameters:
          url: http://113.235.101.11:54384
          provider: crowdstrike
      register: pangea
      tags: ['url']

    - name: Breached Password
      netcraftsmen.pangea.intel:
        token: '{{ token }}'
        domain: '{{ domain }}'
        action: password
        parameters:
          hash_type: '{{ "SHA1" | lower }}'
          hash_prefix: 8f263db9e9e6e7259866281db399e16fac312bbb  # echo -n 'cisco123' | sha1sum
          provider: spycloud
      register: pangea
      tags: ['password']